# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class BranchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deposit = channel.unary_unary(
                '/Branch/Deposit',
                request_serializer=service__pb2.DepositRequest.SerializeToString,
                response_deserializer=service__pb2.DepositResponse.FromString,
                )
        self.Withdraw = channel.unary_unary(
                '/Branch/Withdraw',
                request_serializer=service__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=service__pb2.WithdrawResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/Branch/Query',
                request_serializer=service__pb2.QueryRequest.SerializeToString,
                response_deserializer=service__pb2.QueryResponse.FromString,
                )
        self.WithdrawPropogate = channel.unary_unary(
                '/Branch/WithdrawPropogate',
                request_serializer=service__pb2.WithdrawPropogateRequest.SerializeToString,
                response_deserializer=service__pb2.WithdrawPropogateResponse.FromString,
                )
        self.DepositPropogate = channel.unary_unary(
                '/Branch/DepositPropogate',
                request_serializer=service__pb2.DepositPropogateRequest.SerializeToString,
                response_deserializer=service__pb2.DepositPropogateResponse.FromString,
                )


class BranchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Deposit(self, request, context):
        """Branch Services 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawPropogate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DepositPropogate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=service__pb2.DepositRequest.FromString,
                    response_serializer=service__pb2.DepositResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=service__pb2.WithdrawRequest.FromString,
                    response_serializer=service__pb2.WithdrawResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=service__pb2.QueryRequest.FromString,
                    response_serializer=service__pb2.QueryResponse.SerializeToString,
            ),
            'WithdrawPropogate': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawPropogate,
                    request_deserializer=service__pb2.WithdrawPropogateRequest.FromString,
                    response_serializer=service__pb2.WithdrawPropogateResponse.SerializeToString,
            ),
            'DepositPropogate': grpc.unary_unary_rpc_method_handler(
                    servicer.DepositPropogate,
                    request_deserializer=service__pb2.DepositPropogateRequest.FromString,
                    response_serializer=service__pb2.DepositPropogateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Branch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Branch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Branch/Deposit',
            service__pb2.DepositRequest.SerializeToString,
            service__pb2.DepositResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Branch/Withdraw',
            service__pb2.WithdrawRequest.SerializeToString,
            service__pb2.WithdrawResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Branch/Query',
            service__pb2.QueryRequest.SerializeToString,
            service__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WithdrawPropogate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Branch/WithdrawPropogate',
            service__pb2.WithdrawPropogateRequest.SerializeToString,
            service__pb2.WithdrawPropogateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DepositPropogate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Branch/DepositPropogate',
            service__pb2.DepositPropogateRequest.SerializeToString,
            service__pb2.DepositPropogateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
